### PR TITLE
 fix: map content overflowing on small viewports

### PR DESCRIPTION
**Pull request by plr108**
On small viewports (e.g., 320px, iPhone 5) the map was overflowing
and covering the "Let's Connect" message.  Add container div for map
with height of 400px.  Change height of mapDiv to default setting
(auto) to allow room on small viewports for header text and the map.

### CODE REVIEW

**Comment by plr108** [comment]
On small viewports (e.g., 320px, iPhone 5) the map was overflowing
and covering the "Let's Connect" message. Add container div for map
with height of 400px. Change height of mapDiv to default setting
(auto) to allow room on small viewports for header text and the map.  

Note: This commit is the same as the previous pull request except the 
original README file is present in this commit.

**Comment by cameronwp** [comment]
I like this plan. Could you resubmit with the container present in the HTML?

**Comment by plr108** [comment]
Hi Cam!  I created a new pull request (#192) that adds the container div in index.html.  Please let me know if you have any questions or issues, or if I missed something!

Patrick Roche
Proud February 2016 FEND grad, JavaScript Developer with OpenArc

**Comment by cameronwp** [comment]
Cool! Closing this one.

**Pull request closed without merging**
