### PR TITLE
resume

### PR DESCRIPTION
**Pull request by posouza**
done!

### CODE REVIEW

**Comment by posouza** [comment]
done!

**Comment by Wendellej** [comment]
Posouza, I working on Building my Resume.  Java Foundations section, Lesson 9 Data Types.  I'm attempting to complete one of my quizes (Format Data, Build a Resume Header) basically I updating the Header Section w/ my personal info.   But all o the fields that i need to update aren't in the header section so all of the strings that i'm trying to add, append and replace are failing.  Do I just go ahead and manually add the info into the header section of my HTML doc. or am i missing something and attempting to add the information incorrectly?   Here's my JS code to add My Name and My Role:  I may have misunderstood the directions or gotten some of my code syntax wrong.  can you shed some light w/ some additional instructions.  Thx

var formattedName = "Wendell E. Jackson";
var formattedRole = "Web Designer";

var newFormattedName = HTMLheaderName.replace("%data%",  "Wendell E. Jackson"); 
var newFormattedRole = HTMLheaderRole.replace("%data%",  "Web Designer");

//var myHeaders = 
myHeaders.append("Wendell E. Jackson", "Web Designer");

**Comment by Wendellej** [comment]
Well, I just re-ran everything and ran my console cmds just to see if I got any data back and i did.    I was looking for updates to be made to the HTML Index file.   oh, I fixed my myHeaders syntax/

**Comment by daihoun** [comment]
Can u share your resume program with me?

**Pull request closed without merging**
